# Generated by Django 6.0.2 on 2026-03-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('kit', 'Kit'), ('herramienta', 'Herramienta'), ('botiquin', 'Botiquín'), ('mapa', 'Mapa')], max_length=20)),
                ('nivel_recomendado', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('nivel_experiencia', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20)),
                ('ubicacion_climatica', models.CharField(choices=[('frio', 'Frío'), ('templado', 'Templado'), ('calido', 'Cálido'), ('selva', 'Selva'), ('desertico', 'Desértico')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KitEspecializado',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.producto')),
                ('entorno', models.CharField(choices=[('montana', 'Montaña'), ('selva', 'Selva'), ('urbano', 'Urbano'), ('desierto', 'Desierto'), ('nieve', 'Nieve')], max_length=20)),
                ('lista_items', models.JSONField(blank=True, default=list)),
            ],
            bases=('blog.producto',),
        ),
        migrations.CreateModel(
            name='ReservaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_kit', to='blog.usuario')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='blog.kitespecializado')),
            ],
        ),
    ]
