// ============================================================
// mockData.js — Datos simulados para desarrollo frontend
// Cuando el backend esté listo, este archivo se elimina y
// api.js hará llamadas reales a los endpoints.
// ============================================================

export const MOCK_POSTS = [
  {
    id: 1,
    title: "Cómo construir un refugio de emergencia en menos de 2 horas",
    author: "ShadowWolf_82",
    avatar: "🐺",
    content: "En situaciones extremas, el tiempo es tu mayor enemigo. Aquí te explico paso a paso cómo levantar un refugio funcional usando solo ramas, hojas y lo que encuentres en el bosque...",
    tags: ["refugio", "emergencia", "bosque"],
    likes: 142,
    comments: 37,
    date: "2025-11-03",
    isPremium: false,
  },
  {
    id: 2,
    title: "Guía definitiva: agua potable sin filtros modernos",
    author: "IronNomad",
    avatar: "🔥",
    content: "El agua contaminada mata más personas que la mayoría de desastres naturales. Aprende a purificarla con métodos ancestrales que han salvado vidas durante siglos...",
    tags: ["agua", "purificación", "supervivencia"],
    likes: 98,
    comments: 21,
    date: "2025-11-07",
    isPremium: false,
  },
  {
    id: 3,
    title: "Kit de primeros auxilios que REALMENTE necesitas",
    author: "MedicViper",
    avatar: "⚕️",
    content: "Olvida los kits genéricos de farmacia. Este listado ha sido refinado durante 10 años de experiencia en zonas de conflicto y desastres naturales...",
    tags: ["médico", "kit", "primeros auxilios"],
    likes: 204,
    comments: 58,
    date: "2025-11-10",
    isPremium: true,
  },
  {
    id: 4,
    title: "Señales con espejo: comunicación de largo alcance sin tecnología",
    author: "GhostTracker",
    avatar: "👁️",
    content: "Un simple espejo puede enviar señales a más de 15km de distancia. Técnica olvidada que los militares siguen entrenando porque funciona cuando todo lo demás falla...",
    tags: ["comunicación", "señales", "técnicas"],
    likes: 67,
    comments: 14,
    date: "2025-11-12",
    isPremium: false,
  },
  {
    id: 5,
    title: "Navegación nocturna sin GPS: las estrellas como mapa",
    author: "DarkForest",
    avatar: "🌙",
    content: "Durante miles de años los humanos cruzaron continentes usando solo el cielo. Esta habilidad no debería perderse. Te enseño a identificar las constelaciones clave...",
    tags: ["navegación", "astronomía", "nocturno"],
    likes: 183,
    comments: 44,
    date: "2025-11-15",
    isPremium: true,
  },
];

export const MOCK_KITS = [
  {
    id: 1,
    name: "Kit Básico de Supervivencia",
    price: 49.99,
    image: "🎒",
    description: "Todo lo esencial para las primeras 72 horas en cualquier emergencia. Compacto, ligero y resistente al agua.",
    items: ["Linterna táctica", "Silbato de señal", "Manta térmica", "Cuerda paracord 10m", "Encendedor impermeable"],
    stock: 15,
    badge: null,
  },
  {
    id: 2,
    name: "Kit de Filtración de Agua",
    price: 34.99,
    image: "💧",
    description: "Filtra hasta 1000 litros de agua de cualquier fuente. Elimina bacterias, protozoos y partículas.",
    items: ["Filtro LifeStraw", "Tabletas purificadoras x20", "Bolsa colapsable 2L", "Instrucciones de campo"],
    stock: 28,
    badge: null,
  },
  {
    id: 3,
    name: "Kit Táctico Avanzado",
    price: 129.99,
    image: "⚔️",
    description: "Para supervivientes experimentados. Incluye herramientas de grado militar seleccionadas por expertos.",
    items: ["Cuchillo multiusos Gerber", "Hacha plegable", "Kit médico compacto", "Brújula profesional", "Radio de emergencia", "Ración de emergencia 3 días"],
    stock: 7,
    badge: "BESTSELLER",
  },
  {
    id: 4,
    name: "Kit Médico de Campo",
    price: 74.99,
    image: "🩺",
    description: "Diseñado con paramédicos militares. Para tratar heridas graves cuando no hay ayuda profesional disponible.",
    items: ["Torniquete CAT", "Vendajes hemostáticos", "Guías de sutura", "Antisépticos", "Analgésicos de campo", "Manual de primeros auxilios"],
    stock: 12,
    badge: "PREMIUM",
  },
];

export const MOCK_COURSES = [
  {
    id: 1,
    title: "Supervivencia Urbana: Preparación para Desastres",
    instructor: "Carlos 'Iron' Mendez",
    duration: "6 horas",
    level: "Principiante",
    price: 29.99,
    image: "🏙️",
    description: "Aprende a prepararte para terremotos, apagones prolongados y colapsos de infraestructura en entornos urbanos.",
    students: 1240,
    rating: 4.8,
    isPremium: false,
  },
  {
    id: 2,
    title: "Bushcraft: Vivir en el Monte sin Equipamiento Moderno",
    instructor: "Ana 'Wildroot' Torres",
    duration: "12 horas",
    level: "Intermedio",
    price: 59.99,
    image: "🌲",
    description: "Domina las técnicas ancestrales de los nativos americanos adaptadas al mundo moderno. Fuego, refugio, agua, comida.",
    students: 873,
    rating: 4.9,
    isPremium: false,
  },
  {
    id: 3,
    title: "Medicina de Emergencia para No Médicos",
    instructor: "Dr. Raúl Vega",
    duration: "8 horas",
    level: "Avanzado",
    price: 0,
    image: "🏥",
    description: "Contenido exclusivo para suscriptores premium. Tratamiento de heridas graves, reconocimiento de enfermedades críticas y decisiones de triage.",
    students: 456,
    rating: 5.0,
    isPremium: true,
  },
  {
    id: 4,
    title: "Navegación y Orientación sin Tecnología",
    instructor: "Marco 'Pathfinder' Díaz",
    duration: "4 horas",
    level: "Principiante",
    price: 19.99,
    image: "🧭",
    description: "Brújula, mapas topográficos, lectura de estrellas y orientación por el sol. Nunca más te perderás.",
    students: 2105,
    rating: 4.7,
    isPremium: false,
  },
  {
    id: 5,
    title: "Caza, Pesca y Recolección: Alimentarte en el Salvaje",
    instructor: "Elena 'Hunter' Reyes",
    duration: "10 horas",
    level: "Avanzado",
    price: 0,
    image: "🎯",
    description: "Contenido exclusivo premium. Técnicas reales de caza con trampas, pesca de supervivencia y plantas comestibles.",
    students: 312,
    rating: 4.9,
    isPremium: true,
  },
];

export const MOCK_SUBSCRIPTIONS = [
  {
    id: 1,
    name: "FREE",
    price: 0,
    period: "para siempre",
    badge: null,
    badgeIcon: null,
    color: "#6b7280",
    features: [
      "Acceso al foro público",
      "Ver posts básicos",
      "Acceso a cursos gratuitos",
      "Comprar en la tienda",
    ],
    locked: [],
  },
  {
    id: 2,
    name: "SURVIVOR PRO",
    price: 9.99,
    period: "mes",
    badge: "⚡ SURVIVOR",
    badgeIcon: "⚡",
    color: "#f59e0b",
    features: [
      "Todo lo de FREE",
      "Badge exclusivo ⚡ en el foro",
      "Acceso a posts premium",
      "Todos los cursos desbloqueados",
      "Descuentos 15% en tienda",
      "Chat privado con instructores",
    ],
    locked: [],
    popular: true,
  },
  {
    id: 3,
    name: "ELITE GHOST",
    price: 24.99,
    period: "mes",
    badge: "💀 GHOST",
    badgeIcon: "💀",
    color: "#ef4444",
    features: [
      "Todo lo de SURVIVOR PRO",
      "Badge 💀 GHOST exclusivo",
      "Acceso anticipado a nuevos cursos",
      "Descuentos 30% en tienda",
      "Sesiones 1:1 con expertos",
      "Comunidad privada Discord",
      "Kit físico de bienvenida",
    ],
    locked: [],
  },
];
